plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'kotlin-kapt'
    id 'org.greenrobot.greendao' // apply plugin
}

android {
    namespace 'com.zhuowei.polling'
    compileSdk rootProject.ext.compileSdkVersion

    defaultConfig {

        applicationId "com.zhuowei.polling"
        minSdk rootProject.ext.minSdkVersion
        targetSdk rootProject.ext.targetSdkVersion
        versionCode rootProject.ext.versionCode
        versionName rootProject.ext.versionName

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        multiDexEnabled true

        defaultConfig {
            ndk {
                abiFilters "armeabi", "armeabi-v7a", "arm64-v8a"
            }
        }
    }

    applicationVariants.all { variant ->
        variant.outputs.all {
            outputFileName = "polling_${variant.versionName}.apk"
        }
    }


    signingConfigs {
        normalConfig {
            storeFile file('keystore/debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }


    }


    flavorDimensions "default"
    productFlavors {
        normal {
            signingConfig signingConfigs.normalConfig
            manifestPlaceholders = [shared_id  : "",
                                    orientation: "portrait"]
        }


    }


    buildTypes {
        debug {
//            signingConfig signingConfigs.releaseConfig
            signingConfig null
            minifyEnabled false


        }
        release {
            minifyEnabled false
            signingConfig null
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    dataBinding {
        enabled = true
    }


    greendao {
        schemaVersion 1
        targetGenDir 'src/main/java'
        daoPackage 'com.zhuowei.polling.db.greendao'
    }
}

dependencies {

    implementation fileTree(include: ['*.aar', '*.jar'], dir: 'libs')

    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation "androidx.core:core-ktx:$ktx_version"
    implementation "androidx.appcompat:appcompat:$appcompat_version"
    implementation "com.google.android.material:material:$material_version"
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'

    implementation 'io.github.yuweiguocn:GreenDaoUpgradeHelper:v2.2.1'
    implementation 'org.greenrobot:greendao:3.3.0'
    implementation 'com.tencent.bugly:crashreport:latest.release'//bugly
    implementation 'com.android.support:multidex:1.0.2'

    implementation 'io.github.h07000223:flycoTabLayout:3.0.0'
    implementation 'com.kyleduo.switchbutton:library:2.1.0'

    implementation("com.github.chenlx761:project_common:v1.0.5")

    implementation('com.github.bumptech.glide:okhttp3-integration:4.9.0', {
        //exclude module:
        exclude group: 'com.squareup.okhttp3'
    })

    implementation 'com.google.code.gson:gson:2.8.5'
    //eventbus
    implementation 'org.greenrobot:eventbus:3.1.1'

    implementation 'com.guolindev.permissionx:permissionx:1.6.0'

    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.5.2'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.2'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:2.3.1"
    implementation "androidx.lifecycle:lifecycle-runtime-ktx:2.3.1"
    implementation "androidx.fragment:fragment-ktx:1.2.5"
    implementation "androidx.lifecycle:lifecycle-livedata:2.3.1"
    implementation 'com.github.ybq:Android-SpinKit:1.4.0'
    implementation 'com.blankj:utilcodex:1.30.5'
    implementation 'com.github.chenlx761:http_lib:v1.0.2'

    kapt "com.android.databinding:compiler:3.1.4"
    implementation 'com.alibaba:fastjson:1.2.49'
    implementation 'io.github.scwang90:refresh-header-material:2.0.5'
    implementation 'io.github.h07000223:flycoTabLayout:3.0.0'
    implementation 'com.contrarywind:Android-PickerView:4.1.9'
    implementation 'cn.aigestudio.wheelpicker:WheelPicker:1.1.3'

    implementation 'com.baidu.lbsyun:BaiduMapSDK_Location:9.6.4'
    implementation project(path: ':hudun')

    implementation  'io.github.scwang90:refresh-layout-kernel:3.0.0-alpha'      //核心必须依赖
    implementation  'io.github.scwang90:refresh-header-material:3.0.0-alpha'    //谷歌刷新头
    implementation  'io.github.scwang90:refresh-footer-ball:3.0.0-alpha'        //球脉冲加载
}